config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'
  get 'about' => 'home#about'

  # Concerns
  concern :commentable do
    resources :comments, except: [:new, :show]
    get '/comments/reply/:id' => 'comments#reply', as: :reply_comment
  end
  get '/comments/:id/show_parent' => 'comments#show_parent', as: :show_parent_comment
  concern :collectable do
    get '/collect' => 'collections#collect', as: :collect
    get '/uncollect' => 'collections#uncollect', as: :uncollect
  end
  get '/collections/:id/view' => 'collections#view', as: :collection_view
  # 用户
  devise_for :users, path_prefix: 'd',
    controllers: {
      sessions:      'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords:     'users/passwords',
      emails:        'users/emails'
    }
  resources :users, except: [:show, :edit] do
    get 'mailbox/index'
    get 'mailbox/reply_message/:id' => 'mailbox#reply_message', as: :reply_message
    get 'mailbox/write_message' => 'mailbox#write_message', as: :write_message
    post 'mailbox/send_message' => 'mailbox#send_message', as: :send_message
    get 'mailbox/delete_message/:id' => 'mailbox#delete_message', as: :delete_message
    get 'mailbox/delete_notification/:id' => 'mailbox#delete_notification', as: :delete_notification
    get 'mailbox/empty_trash' => 'mailbox#empty_trash', as: :empty_trash
    get 'mailbox/restore_message/:id' => 'mailbox#restore_message', as: :restore_message
    get 'following' => 'relationships#following', as: :following
    get 'followers' => 'relationships#followers', as: :followers
    resources :achievements
    resources :experiences
    resources :user_options
    resources :user_quota
  end
  get 'users/:id/home_page' => 'users#show_home_page', as: :show_user_home_page
  get 'users/:id/(:category)' => 'users#show', as: :show_user
  get 'users/:id/edit/(:category)' => 'users#edit', as: :edit_user
  get 'follow/:followed_id' => 'relationships#follow', as: :follow_user
  get 'unfollow/:followed_id' => 'relationships#unfollow', as: :unfollow_user
  # 文章
  resources :articles, concerns: [:commentable, :collectable]
  post 'articles/upload_image' => 'articles#upload_image', as: :article_upload_image
  # 资源
  resources :resources, concerns: [:commentable, :collectable]
  resources :folders
  [:delete_files, :rename_file, :move_files, :share_files].each do |action|
    get "#{action}/:folderable_type/:folderable_id" => "resource_board##{action}", as: action
  end
  resources :shares do
    member do
      get :back_to_top
    end
  end
  # 参考文献
  resources :publications, except: [:index, :new, :edit, :show]
  resources :references
  resources :publishers
  # 资格
  resources :memberships do
    member do
      get :reject
    end
  end
  # 群组
  resources :nodes
  resources :topics, except: [:new], concerns: [:commentable, :collectable]
  post 'topics/upload_image' => 'topics#upload_image', as: :topic_upload_image # TODO: 放到concerns中。
  resources :groups, except: [:show, :edit] do
    member do
      post :upload_image
    end
    resources :nodes, only: [:edit, :create, :update]
    resources :topics, only: [:new]
  end
  get 'groups/:id/home_page' => 'groups#show_home_page', as: :show_group_home_page
  get 'groups/:id/(:category)' => 'groups#show', as: :show_group
  get 'groups/:id/edit/(:category)' => 'groups#edit', as: :edit_group
  resources :group_options
  resources :activities

  # 控制台
  get 'dashboard' => 'dashboard#index', as: :dashboard
  DashboardController::AdminModels.each do |category|
    get "dashboard/admin/#{category}" => "dashboard#admin_#{category}", as: "admin_#{category}"
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end
end

app/models/node.rb
# == Schema Information
#
# Table name: nodes
#
#  id            :integer          not null, primary key
#  name          :string
#  group_id      :integer
#  parent_id     :integer
#  status        :string
#  position      :integer
#  on_group_page :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Node < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :name, presence: true,  uniqueness: { scope: :group_id }
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_group, only: [:create]
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  def index
    @nodes = @group.nodes.all
  end

  def show
  end

  def new
    @node = @group.nodes.new
  end

  def edit
  end

  def create
    @node = @group.nodes.new(node_params)
    @group.increment! :nodes_count if @node.save
    respond_to do |format|
      format.js
    end
  end

  def update
    @node.update(node_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to session[:previous_url].last }
    end
  end

  private

  def set_group
    @group = Group.friendly.find(params[:group_id])
  end

  def set_node
    @node = Node.find(params[:id])
  end

  def node_params
    params.require(:node).permit(:user_id, :name, :group_id, :status, :position)
  end
end

app/views/nodes/_form.html.erb
<div class='horizontal-centered'>
  <%= simple_form_for [group, node], remote: true do |f| %>
    <%= f.input :name, required: false %>
    <%= f.submit t('action.submit'), class: 'btn btn-success' %>
  <% end %>
</div>

app/views/nodes/_index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">修改节点信息</div>
  <div class="panel-body">

  </div>

  <!-- Table -->
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>名称</th>
      <th>状态</th>
      <th>话题数</th>
      <th>是否出现在主页</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td>1</td>
        <td><%= node.name %></td>
        <td><%= node.status %></td>
        <td><%= node.topics.count %></td>
        <td><%= node.on_group_page %></td>
        <td>
          <%= link_to t('action.edit'), edit_group_node_path(@group, node), remote: true %> |
          <%= link_to t('action.delete'), group_node_path(@group, node), method: :delete,
                      data: { confirm: t('message.are_you_sure_to_delete?', thing: ("#{node.name}")) } %>
        </td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

app/views/nodes/_table_list.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.node.name') %></th>
      <th><%= t('activerecord.attributes.node.topics_count') %></th>
      <th><%= t('activerecord.attributes.node.created_at') %></th>
      <th><%= t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= node.topics_count %></td>
        <td><%= timeago node.created_at %></td>
        <td>
          <% if policy(node).manage? %>
            <ul class='horizontal-clean-list'>
              <li>
                <%= link_to t('action.edit'), edit_group_node_path(@group, node),
                  class: 'btn btn-default btn-xs', remote: true %>
              </li>
              <li>
                <%= link_to t('action.delete'), node,
                  method: :delete, class: 'btn btn-default btn-xs',
                  data: { confirm: t('message.are_you_sure_to_delete?', thing: t('activerecord.models.node')) } %>
              </li>
            </ul>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/nodes/create.js.erb
<% if @node.errors.empty? %>
  window.location.replace('<%= session[:previous_url].last %>')
<% else %>
  handleValidationErrors({
    formName: 'node',
    messages: '<%= j raw @node.errors.messages.to_json %>'
  })
<% end %>

app/views/nodes/edit.js.erb
$('#edit-node-modal-content').html('<%= j render "nodes/form", group: @group, node: @node %>')
$('#edit-node-modal').modal()

app/views/nodes/index.html.erb
<% content_for :title, t('action.edit')+t('activerecord.models.group') %>

<% content_for :center_column do %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'groups/group_left', group: @group %>
    </div>
    <div class="col-md-9">
      <div id="group_node_list">
        <%= render 'nodes/index' %>
      </div>

      <%= link_to t('action.add'), new_group_node_path(@group), remote: true, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/nodes/new.js.erb
$('body').find('#group_node').remove();
$('body').append(<%=  raw render("form", group: @group, node: @node).inspect %> );
$('#group_node').modal('show');

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @node.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @node.group_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @node.status %>
</p>

<p>
  <strong>Position:</strong>
  <%= @node.position %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/update.js.erb
<% if @node.errors.empty? %>
  window.location.replace('<%= session[:previous_url].last %>')
<% else %>
  handleValidationErrors({
    formName: 'node',
    messages: '<%= j raw @node.errors.messages.to_json %>'
  })
<% end %>