config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'
  get 'about' => 'home#about'

  # Concerns
  concern :commentable do
    resources :comments, except: [:new, :show]
    get '/comments/reply/:id' => 'comments#reply', as: :reply_comment
  end
  get '/comments/:id/show_parent' => 'comments#show_parent', as: :show_parent_comment
  concern :collectable do
    get '/collect' => 'collections#collect', as: :collect
    get '/uncollect' => 'collections#uncollect', as: :uncollect
  end
  get '/collections/:id/view' => 'collections#view', as: :collection_view
  # 用户
  devise_for :users, path_prefix: 'd',
    controllers: {
      sessions:      'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords:     'users/passwords',
      emails:        'users/emails'
    }
  resources :users, except: [:show, :edit] do
    get 'mailbox/index'
    get 'mailbox/reply_message/:id' => 'mailbox#reply_message', as: :reply_message
    get 'mailbox/write_message' => 'mailbox#write_message', as: :write_message
    post 'mailbox/send_message' => 'mailbox#send_message', as: :send_message
    get 'mailbox/delete_message/:id' => 'mailbox#delete_message', as: :delete_message
    get 'mailbox/delete_notification/:id' => 'mailbox#delete_notification', as: :delete_notification
    get 'mailbox/empty_trash' => 'mailbox#empty_trash', as: :empty_trash
    get 'mailbox/restore_message/:id' => 'mailbox#restore_message', as: :restore_message
    get 'following' => 'relationships#following', as: :following
    get 'followers' => 'relationships#followers', as: :followers
    resources :achievements
    resources :experiences
    resources :user_options
    resources :user_quota
  end
  get 'users/:id/home_page' => 'users#show_home_page', as: :show_user_home_page
  get 'users/:id/(:category)' => 'users#show', as: :show_user
  get 'users/:id/edit/(:category)' => 'users#edit', as: :edit_user
  get 'follow/:followed_id' => 'relationships#follow', as: :follow_user
  get 'unfollow/:followed_id' => 'relationships#unfollow', as: :unfollow_user
  # 文章
  resources :articles, concerns: [:commentable, :collectable]
  post 'articles/upload_image' => 'articles#upload_image', as: :article_upload_image
  # 资源
  resources :resources, concerns: [:commentable, :collectable]
  resources :folders
  [:delete_files, :rename_file, :move_files, :share_files].each do |action|
    get "#{action}/:folderable_type/:folderable_id" => "resource_board##{action}", as: action
  end
  resources :shares do
    member do
      get :back_to_top
    end
  end
  # 参考文献
  resources :publications, except: [:index, :new, :edit, :show]
  resources :references
  resources :publishers
  # 资格
  resources :memberships do
    member do
      get :reject
    end
  end
  # 群组
  resources :nodes
  resources :topics, except: [:new], concerns: [:commentable, :collectable]
  post 'topics/upload_image' => 'topics#upload_image', as: :topic_upload_image # TODO: 放到concerns中。
  resources :groups, except: [:show, :edit] do
    member do
      post :upload_image
    end
    resources :nodes, only: [:edit, :create, :update]
    resources :topics, only: [:new]
  end
  get 'groups/:id/home_page' => 'groups#show_home_page', as: :show_group_home_page
  get 'groups/:id/(:category)' => 'groups#show', as: :show_group
  get 'groups/:id/edit/(:category)' => 'groups#edit', as: :edit_group
  resources :group_options
  resources :activities

  # 控制台
  get 'dashboard' => 'dashboard#index', as: :dashboard
  DashboardController::AdminModels.each do |category|
    get "dashboard/admin/#{category}" => "dashboard#admin_#{category}", as: "admin_#{category}"
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id                :integer          not null, primary key
#  group_id          :integer
#  node_id           :integer
#  user_id           :integer
#  title             :string
#  content           :text
#  views_count       :integer
#  comments_count    :integer
#  sticky            :boolean
#  essential         :boolean
#  status            :string
#  position          :integer
#  last_edited_at    :datetime
#  last_commented_at :datetime
#  deleted_at        :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Topic < ActiveRecord::Base
  extend Enumerize
  enumerize :status, in: [:public, :private, :closed], default: :public, predicates: true

  belongs_to :user
  belongs_to :group
  belongs_to :node
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :collections, as: :collectable, dependent: :destroy

  delegate :name, :email, to: :user, prefix: :user, allow_nil: true

  validates :node_id, :title, :content, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def show
    @topic.increment!(:views_count)
  end

  def new
    @group = Group.friendly.find(params[:group_id])
    @topic = @group.topics.new
  end

  def edit
    @group = @topic.group
  end

  def create
    @group = Group.friendly.find(params[:topic][:group_id])
    @topic = @group.topics.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        @group.increment! :topics_count
        format.html { redirect_to show_group_path(@group, :topics, node: @topic.node.name) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to show_group_path(@topic.group, :topics) }
    end
  end

  def upload_image
    file = params[:file]
    image = current_user.resources.new(name: SecureRandom.hex,
                                       resourceable_type: 'User',
                                       resourceable_id: current_user.id,
                                       user_id: current_user.id,
                                       status: 'hidden',
                                       file: file)
    image.save!
    respond_to do |format|
      format.json { render json: { link: image.file.url } }
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:user_id, :group_id, :node_id, :title,  :content, :status, :position)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class='panel panel-default box-shadow'>
  <div class='panel-body'>
    <%= simple_form_for @topic do |f| %>
      <%= f.hidden_field :group_id, value: @group.id %>
      <%= f.input :title, required: false %>
      <div class='row'>
        <div class='col-md-6'>
          <%= f.association :node, collection: @group.nodes, required: false %>
        </div>
        <div class='col-md-6'>
          <%= f.input :status %>
        </div>
      </div>
      <%= f.input :content, required: false %>
      <%= f.button :submit, t('action.submit'), class: 'btn btn-success pull-right' %>
    <% end %>
  </div>
</div>
<script>
  $(function() {
    $('#topic_content').froalaEditor({
      height: '300',
      imageUploadURL: '<%= topic_upload_image_path %>',
      imageUploadParams: {
        authenticity_token: '<%= form_authenticity_token %>',
        return_to: window.location.href
      },
      imageAllowedTypes: ['jpeg', 'jpg', 'png']
    })
  });
</script>

app/views/topics/_table_list.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th width='100'><%= t('activerecord.attributes.topic.title') %></th>
      <th width='50'><%= t('activerecord.attributes.topic.user') %></th>
      <th width='50'><%= t('activerecord.attributes.topic.created_at') %></th>
    </tr>
  </thead>
  <tbody>
    <% topics.each do |topic| %>
      <tr class='clickable-row' data-href='<%= topic_path(topic) %>'>
        <td><%= "《#{topic.title}》" %></td>
        <td><%= link_to topic.user.name, topic.user %></td>
        <td><%= timeago topic.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/topics/_topic.html.erb
<div class="panel panel-info">
  <div class="panel-body">
    <div class="topic"></div>
  </div>

  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>

</div>

app/views/topics/edit.html.erb
<% content_for :center_column do %>
  <%= render 'form' %>
<% end %>

app/views/topics/index.html.erb
<% content_for :left_column do %>
  <%= render 'groups/profile_left' %>
<% end %>

<% content_for :center_column do %>
  <% is_in_group = is_in_group? @group %>
  <ul class='horizontal-line-list'>
    <% if @topics.empty? %>
      <div class='horizontal-centered'>还没有任何话题哦。</div>
    <% else %>
      <% @topics.order('id DESC').each do |topic| %>
        <% next if not is_in_group and topic.private? %>
        <li>
          <div class='row'>
            <div class='col-xs-1'>
              <%= avatar topic.user, size: '50x50' %>
            </div>
            <div class='col-xs-11'>
              <span style='display: inline-block; margin-left: 1em;'>
                <%= link_to topic.title, topic %><br/>
                <span class='label label-default'><%= topic.node.name %></span>
                <%= fa_icon 'comment-o', text: topic.comments_count, style: 'margin-left: 1em;' %>
                <%= fa_icon 'eye', text: topic.views_count, style: 'margin-left: 1em;' %>
              </span>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/topics/new.html.erb
<% content_for :center_column do %>
  <%= render 'form' %>
<% end %>

app/views/topics/post_to_groups.js.erb
$('input[id^=group-]').each(function () {
  // 只有当群组被选中，并且还没有贴出该对象时才执行发布操作。
  if ($(this).prop('checked') && ! $(this).prop('disabled')) {
    group_id = $(this).attr('id').split('-')[1];
    $('#new-topic-for-group-' + group_id).trigger('click');
  }
});
// 关闭弹出框。
$('#select-groups').modal('hide');

app/views/topics/show.html.erb
<% content_for :title, @topic.title %>

<% content_for :center_column do %>
<div class='panel panel-default box-shadow'>
  <div class='panel-body'>
    <div style='margin-bottom: 10px;'>
      <ul class='horizontal-clean-list' style='display: inline-block;'>
        <li><%= link_to image_tag(@topic.user.profile.avatar_url(:thumb)), @topic.user %></li>
        <li>更新于<%= timeago @topic.updated_at %></li>
      </ul>
      <div class='pull-right' style='padding-top: 10px;'>
        <ul class='horizontal-clean-list'>
          <% if policy(@topic).update? %>
            <li><%= link_to fa_icon('edit'), edit_topic_path(@topic) %></li>
          <% end %>
          <% if policy(@topic).destroy? %>
            <li>
              <%= link_to fa_icon('trash'), topic_path(@topic), method: :delete,
                data: { confirm: t('message.are_you_sure_to_delete?', thing: t('activerecord.models.topic')) } %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li><%= render 'collections/collect_button', collectable: @topic %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <h6 class='horizontal-centered'><%= @topic.title %></h6>
    <div class='row'>
      <div class='col-md-8 col-md-offset-2'>
        <div class='mathjax'><%= raw @topic.content %></div>
      </div>
    </div>
    <dl>
      <dt></dt>
      <dd><%= render 'comments/list', commentable: @topic %></dd>
    </dl>
  </div>
</div>
<% end %>