config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'
  get 'about' => 'home#about'

  # Concerns
  concern :commentable do
    resources :comments, except: [:new, :show]
    get '/comments/reply/:id' => 'comments#reply', as: :reply_comment
  end
  get '/comments/:id/show_parent' => 'comments#show_parent', as: :show_parent_comment
  concern :collectable do
    get '/collect' => 'collections#collect', as: :collect
    get '/uncollect' => 'collections#uncollect', as: :uncollect
  end
  get '/collections/:id/view' => 'collections#view', as: :collection_view
  # 用户
  devise_for :users, path_prefix: 'd',
    controllers: {
      sessions:      'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords:     'users/passwords',
      emails:        'users/emails'
    }
  resources :users, except: [:show, :edit] do
    get 'mailbox/index'
    get 'mailbox/reply_message/:id' => 'mailbox#reply_message', as: :reply_message
    get 'mailbox/write_message' => 'mailbox#write_message', as: :write_message
    post 'mailbox/send_message' => 'mailbox#send_message', as: :send_message
    get 'mailbox/delete_message/:id' => 'mailbox#delete_message', as: :delete_message
    get 'mailbox/delete_notification/:id' => 'mailbox#delete_notification', as: :delete_notification
    get 'mailbox/empty_trash' => 'mailbox#empty_trash', as: :empty_trash
    get 'mailbox/restore_message/:id' => 'mailbox#restore_message', as: :restore_message
    get 'following' => 'relationships#following', as: :following
    get 'followers' => 'relationships#followers', as: :followers
    resources :achievements
    resources :experiences
    resources :user_options
    resources :user_quota
  end
  get 'users/:id/home_page' => 'users#show_home_page', as: :show_user_home_page
  get 'users/:id/(:category)' => 'users#show', as: :show_user
  get 'users/:id/edit/(:category)' => 'users#edit', as: :edit_user
  get 'follow/:followed_id' => 'relationships#follow', as: :follow_user
  get 'unfollow/:followed_id' => 'relationships#unfollow', as: :unfollow_user
  # 文章
  resources :articles, concerns: [:commentable, :collectable]
  post 'articles/upload_image' => 'articles#upload_image', as: :article_upload_image
  # 资源
  resources :resources, concerns: [:commentable, :collectable]
  resources :folders
  [:delete_files, :rename_file, :move_files, :share_files].each do |action|
    get "#{action}/:folderable_type/:folderable_id" => "resource_board##{action}", as: action
  end
  resources :shares do
    member do
      get :back_to_top
    end
  end
  # 参考文献
  resources :publications, except: [:index, :new, :edit, :show]
  resources :references
  resources :publishers
  # 资格
  resources :memberships do
    member do
      get :reject
    end
  end
  # 群组
  resources :nodes
  resources :topics, except: [:new], concerns: [:commentable, :collectable]
  post 'topics/upload_image' => 'topics#upload_image', as: :topic_upload_image # TODO: 放到concerns中。
  resources :groups, except: [:show, :edit] do
    member do
      post :upload_image
    end
    resources :nodes, only: [:edit, :create, :update]
    resources :topics, only: [:new]
  end
  get 'groups/:id/home_page' => 'groups#show_home_page', as: :show_group_home_page
  get 'groups/:id/(:category)' => 'groups#show', as: :show_group
  get 'groups/:id/edit/(:category)' => 'groups#edit', as: :edit_group
  resources :group_options
  resources :activities

  # 控制台
  get 'dashboard' => 'dashboard#index', as: :dashboard
  DashboardController::AdminModels.each do |category|
    get "dashboard/admin/#{category}" => "dashboard#admin_#{category}", as: "admin_#{category}"
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id            :integer          not null, primary key
#  logo          :string
#  admin_id      :integer
#  status        :string
#  members_count :integer
#  topics_count  :integer
#  nodes_count   :integer
#  position      :integer
#  deleted_at    :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Group < ActiveRecord::Base
  include Resourceable

  extend Enumerize
  enumerize :status, in: [ :public, :private ], default: :public, predicates: true

  extend FriendlyId
  friendly_id :slug, use: :slugged

  mount_uploader :logo, LogoUploader

  # 使用Jcrop裁剪头像，下面这四个变量是存储裁剪参数。
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  acts_as_taggable
  acts_as_taggable_on :categories

  translates :name, :short_name, :description

  has_many :memberships, as: :host, dependent: :destroy
  has_many :users, class_name: 'User', through: :memberships
  has_many :topics, dependent: :destroy
  has_many :nodes, dependent: :destroy

  validates :name, :short_name, presence: true, uniqueness: true
  validates :slug, uniqueness: true, if: :slug?
  validates :slug, format: { with: /[a-zA-Z_][a-zA-Z0-9_]+/, allow_blank: true }
  validates :logo, file_size: { less_than_or_equal_to: 2.megabytes },
                   file_content_type: { allow: [ 'image/jpeg', 'image/png' ] }

  after_create :create_default_associated_models

  def admin
    if not defined? @admin or @admin.id != self.admin_id
      @admin = User.find(self.admin_id)
    else
      @admin
    end
  end

  private

  def create_default_associated_models
    # 创建默认节点。
    [:news, :achievements, :chat].each do |node|
      node = Node.create name: I18n.t("node.defaults.#{node}"), group_id: self.id
      self.nodes << node
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :members, :upload_image]

  def index
    @search = Group.with_translations(I18n.locale).ransack(params[:q])
    @groups = @search.result.includes(:taggings).order(:id).page(params[:page])
  end

  def show
    @category = params[:category] || 'profile'
    case @category
    when 'topics'
      if params[:node].present?
        @node = params[:node]
        node_id = @group.nodes.where(name: @node)
        @topics = @group.topics.where(node_id: node_id).page(params[:page])
      else
        @search = @group.topics.search(params[:q])
        @topics = @search.result.page(params[:page])
      end
    when 'memberships'
      @search = @group.memberships.search(params[:q])
      @memberships = @search.result.page(params[:page])
    end
  end

  def new
    @group = Group.new
  end

  def edit
    @category = params[:category]
    case @category
    when 'memberships'
      if params[:status].present?
        @status = params[:status] || 'unapproved'
        @memberships = @group.memberships.where(status: @status).page(params[:page])
      else
        @search = @group.memberships.search(params[:q])
        @memberships = @search.result.page(params[:page])
      end
    end
  end

  def create
    @group = Group.new(group_params)
    set_crop_params
    # 创建组织的用户默认成为管理者。
    @group.admin_id = current_user.id
    respond_to do |format|
      if @group.save
        @membership = current_user.memberships.create(host_type: 'Group', host_id: @group.id, role: "admin", status: "approved")
        format.html { redirect_to @group }
      else
        format.html { render :new }
      end
    end
  end

  def update
    set_crop_params
    @category = params[:group][:category]
    @group.update(group_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def feed
    group_ids = Membership.where(user_id: current_user.id, host_type: "Group", status: "approved").pluck(:host_id)
    @topics = Topic.includes(:user).where(group_id: group_ids).order('updated_at desc')
    @posts = Post.includes(:postable).where(group_id: group_ids).order('updated_at desc')
  end

  def members
    @members = Kaminari.paginate_array(@group.memberships.where(status: 'approved').map { |x| x.user }).page(params[:page])
  end

  def upload_image
    file = params[:file]
    image = current_user.resources.new(name: SecureRandom.hex,
                                       resourceable_type: 'Group',
                                       resourceable_id: @group.id,
                                       user_id: current_user.id,
                                       status: 'hidden',
                                       file: file)
    image.save!
    respond_to do |format|
      format.json { render json: { link: image.file.url } }
    end
  end

  private

  def set_crop_params
    if params[:group][:crop_x].present?
      @group.crop_x = params[:group][:crop_x]
      @group.crop_y = params[:group][:crop_y]
      @group.crop_w = params[:group][:crop_w]
      @group.crop_h = params[:group][:crop_h]
    end
  end

  def set_group
    @group = Group.friendly.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name,
                                  :short_name,
                                  :logo,
                                  :slug,
                                  :description,
                                  :admin_id,
                                  { article_ids: [] },
                                  :tag_list,
                                  { category_list: [] },
                                  :status)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def is_in_groups? groups
    current_user and not (current_user.groups & groups).empty?
  end

  def is_in_group? group
    current_user and current_user.groups.include? group
  end

  def get_valid_groups_of user
    user.memberships.where(host_type: 'Group', status: 'approved').map { |x| x.host }
  end
end

app/views/groups/_block_list.html.erb
<% only_logo = false if local_assigns[:only_logo].nil? %>
<div class='row'>
  <% groups.each do |group| %>
    <% if only_logo %>
      <a href='<%= group_path(group) %>'>
        <%= logo group, size: :thumb %>
      </a>
    <% else %>
      <div class='col-md-3 col-sm-4 col-xs-6'>
        <div class='panel panel-default box-shadow'>
          <div class='panel-body horizontal-centered'>
            <%= link_to logo(group, size: :medium), group %><br/>
            <%= group.name %><br/>
            <%= fa_icon 'group', text: group.members_count, style: 'margin-top: 10px;' %>
            <%= fa_icon 'tags', text: group.nodes_count, style: 'margin-left: 5px;' %>
            <%= fa_icon 'comments-o', text: group.topics_count, style: 'margin-left: 5px;' %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class='horizontal-centered'>
  <%= paginate groups %>
</div>

app/views/groups/_form.html.erb
<div class='group-form'>
  <%= simple_form_for(@group) do |f| %>
    <div class='row'>
      <div class='col-md-8'>
        <%= f.input :name, autofocus: true %>
      </div>
      <div class='col-md-4'>
        <%= f.input :short_name %>
      </div>
    </div>
    <%= f.input :category_list, collection: @group.categories.map { |t| t.name },
      input_html: { class: 'use-select2-multiple-tags', multiple: 'multiple' } %>
    <%= f.input :description, as: :text %>

    <%= f.button :submit, t('action.submit'), class: 'btn btn-success uppercase btn-block' %>
  <% end %>
</div>

app/views/groups/_group.html.erb
  <div class="thumbnail">
    <%= image_tag group.logo, height: '150', width: '100%', display: 'block' %>
    <!--<img data-src="holder.js/100%x200" alt="100%x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMzQ4IiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDM0OCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMzQ4IiBoZWlnaHQ9IjIwMCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzMi40ODQzNzUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6I0FBQUFBQTtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxNnB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjM0OHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg==" data-holder-rendered="true" style="height: 150px; width: 100%; ">-->
    <div class="caption">
      <h4><%= group.name %></h4>
      <p><a role="button" class="btn btn-primary" href="#">人数<%= group.members_count || 0 %>人</a>
        <a role="button" class="btn btn-default" href="#">话题<%= group.topics_count || 0 %>个</a>
      </p>
    </div>
  </div>

app/views/groups/_group_left.html.erb
<!--管理群组的左边栏-->
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">群组管理</h3>
  </div>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to edit_group_path(group) do %>修改群组信息<% end %></li>

    <li class="list-group-item">
      <%= link_to group_nodes_path(group) do %>修改节点信息<% end %>
    </li>
    <li class="list-group-item"><%= link_to group_topics_path(group) do %>修改话题信息<% end %></li>
    <li class="list-group-item"><%= link_to group_memberships_path(group) do %>群组成员<% end %></li>
  </ul>
</div>

app/views/groups/_group_right.html.erb
<%#= TODO '获取当前用户加入通过的群组,并且根据某种规则展示多个个群组' %>
<% if current_user %>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">我加入的群组</h3>
    </div>
    <div class="panel-body">
      <% Group.all.each do |group| %>
        <%= render 'groups/group', group: group %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">推荐群组</h3>
    </div>
    <div class="panel-body">
      <% Group.all.each do |group| %>
        <%= render 'groups/group', group: group %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/groups/_table_list.html.erb
<table class='table table-striped'>
  <col width='100'>
  <col width='50'>
  <col width='50'>
  <col width='50'>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.group.name') %></th>
      <th><%= t('activerecord.attributes.group.admin') %></th>
      <th><%= t('activerecord.attributes.group.created_at') %></th>
      <th><%= t('group.member_number') %></th>
    </tr>
  </thead>
  <tbody>
    <% groups.all.each do |group| %>
      <tr class='clickable-row' data-href='<%= group_path(group) %>'>
        <td><%= group.name %></td>
        <td><%= link_to group.admin.name, group.admin %></td>
        <td><%= timeago group.created_at %></td>
        <td><%= group.users.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/broadcast.html.erb
<!-- 群组展示页面-->

app/views/groups/edit.html.erb
<% content_for :left_column do %>
  <div class='panel panel-default box-shadow'>
    <div class='panel-body sidenav'>
      <ul class='nav nav-pills nav-stacked'>
        <% ['profile', 'memberships', 'topics'].each do |category| %>
          <li role='presentation' class='<%= @category == category ? 'active' : '' %>'>
            <%= link_to t("group.show.#{category}"), edit_group_path(@group, category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<% content_for :center_column do %>
  <%= render "groups/edit/#{@category}" %>
<% end %>

app/views/groups/index.html.erb
<% content_for :title, t('activerecord.models.group') %>

<% content_for :center_column do %>
  <div class='search-form'>
    <%= simple_form_for @search, url: groups_path, method: :get do |f| %>
      <%= f.input :translations_name_or_translations_name_cont, label: false, placeholder: '搜索名称',
        wrapper_html: { style: 'display: inline-block;' }, required: false %>
      <%= f.input :taggings_tag_name_in, label: false, placeholder: '搜索标签',
        collection: Group.all_tags, value_method: :name,
        wrapper_html: { style: 'display: inline-block;' },
        input_html: { class: 'use-select2-multiple-tags', multiple: 'multiple' } %>
      <%= f.submit t('action.search'), class: 'btn btn-success', style: 'height: 42px;' %>
      <% if request.params[:q] %>
        <%= link_to t('action.cancel'), groups_path, class: 'btn btn-default', style: 'height: 42px;' %>
      <% end %>
    <% end %>
  </div>
  <%= render 'block_list', groups: @groups %>
<% end %>

<% content_for :right_column do %>
  <div class='panel panel-default box-shadow'>
    <div class='panel-heading'>
      您加入的群组
    </div>
    <div class='panel-body horizontal-centered'>
      <%= render 'block_list', groups: @groups, only_logo: true %>
      <% if policy(Group).create? %>
        <%= link_to fa_icon('plus-square-o', text: t('action.add')), new_group_path %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/groups/new.html.erb
<% content_for :title, t('action.add')+t('activerecord.models.group') %>

<% content_for :center_column do %>
  <div class='panel panel-default box-shadow'>
    <div class='panel-body'>
      <%= render 'form' %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<% content_for :title, @group.name %>

<% content_for :left_column do %>
  <div class='panel panel-default box-shadow'>
    <div class='panel-body horizontal-centered'>
      <ul class='vertical-clean-list'>
        <li><%= link_to logo(@group, size: :medium), @group %></li>
        <li><%= @group.name %></li>
        <li><%= t('activerecord.attributes.group.admin') %>: <%= link_to @group.admin.name, @group.admin %></li>
        <li>
          <ul class='vertical-clean-list'>
            <% @group.categories.each do |tag| %>
              <li><span class='label label-default'>
                <%= tag.name %>
              </span></li>
            <% end %>
          </ul>
        </li>
        <li><%= t('activerecord.attributes.group.created_at')+': '+@group.created_at.strftime("%Y-%-m") %></li>
        <% if policy(@group).update? %>
          <li>
            <%= link_to fa_icon('edit', text: t('action.edit')), edit_group_path(@group, :profile) %>
          </li>
        <% end %>
        <li><%= render 'memberships/apply_button', host: @group %></li>
      </ul>
    </div>
  </div>

  <div class='panel panel-default box-shadow'>
    <div class='panel-body sidenav'>
      <ul class='nav nav-pills nav-stacked'>
        <% ['profile', 'memberships', 'topics'].each do |category| %>
          <li role='presentation' class='<%= @category == category ? 'active' : '' %>'>
            <%= link_to t("group.show.#{category}"), show_group_path(@group, category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<% content_for :center_column do %>
  <%= render "groups/show/#{@category}" %>
<% end %>

app/views/groups/update.js.erb
<% if @group.errors.empty? %>
  window.location.replace('<%= session[:previous_url].last %>')
<% else %>
  handleValidationErrors({
    formName: 'group',
    messages: '<%= j raw @group.errors.messages.to_json %>'
  })
<% end %>