config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'
  get 'about' => 'home#about'

  # Concerns
  concern :commentable do
    resources :comments, except: [:new, :show]
    get '/comments/reply/:id' => 'comments#reply', as: :reply_comment
  end
  get '/comments/:id/show_parent' => 'comments#show_parent', as: :show_parent_comment
  concern :collectable do
    get '/collect' => 'collections#collect', as: :collect
    get '/uncollect' => 'collections#uncollect', as: :uncollect
  end
  get '/collections/:id/view' => 'collections#view', as: :collection_view
  # 用户
  devise_for :users, path_prefix: 'd',
    controllers: {
      sessions:      'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords:     'users/passwords',
      emails:        'users/emails'
    }
  resources :users, except: [:show, :edit] do
    get 'mailbox/index'
    get 'mailbox/reply_message/:id' => 'mailbox#reply_message', as: :reply_message
    get 'mailbox/write_message' => 'mailbox#write_message', as: :write_message
    post 'mailbox/send_message' => 'mailbox#send_message', as: :send_message
    get 'mailbox/delete_message/:id' => 'mailbox#delete_message', as: :delete_message
    get 'mailbox/delete_notification/:id' => 'mailbox#delete_notification', as: :delete_notification
    get 'mailbox/empty_trash' => 'mailbox#empty_trash', as: :empty_trash
    get 'mailbox/restore_message/:id' => 'mailbox#restore_message', as: :restore_message
    get 'following' => 'relationships#following', as: :following
    get 'followers' => 'relationships#followers', as: :followers
    resources :achievements
    resources :experiences
    resources :user_options
    resources :user_quota
  end
  get 'users/:id/home_page' => 'users#show_home_page', as: :show_user_home_page
  get 'users/:id/(:category)' => 'users#show', as: :show_user
  get 'users/:id/edit/(:category)' => 'users#edit', as: :edit_user
  get 'follow/:followed_id' => 'relationships#follow', as: :follow_user
  get 'unfollow/:followed_id' => 'relationships#unfollow', as: :unfollow_user
  # 文章
  resources :articles, concerns: [:commentable, :collectable]
  post 'articles/upload_image' => 'articles#upload_image', as: :article_upload_image
  # 资源
  resources :resources, concerns: [:commentable, :collectable]
  resources :folders
  [:delete_files, :rename_file, :move_files, :share_files].each do |action|
    get "#{action}/:folderable_type/:folderable_id" => "resource_board##{action}", as: action
  end
  resources :shares do
    member do
      get :back_to_top
    end
  end
  # 参考文献
  resources :publications, except: [:index, :new, :edit, :show]
  resources :references
  resources :publishers
  # 资格
  resources :memberships do
    member do
      get :reject
    end
  end
  # 群组
  resources :nodes
  resources :topics, except: [:new], concerns: [:commentable, :collectable]
  post 'topics/upload_image' => 'topics#upload_image', as: :topic_upload_image # TODO: 放到concerns中。
  resources :groups, except: [:show, :edit] do
    member do
      post :upload_image
    end
    resources :nodes, only: [:edit, :create, :update]
    resources :topics, only: [:new]
  end
  get 'groups/:id/home_page' => 'groups#show_home_page', as: :show_group_home_page
  get 'groups/:id/(:category)' => 'groups#show', as: :show_group
  get 'groups/:id/edit/(:category)' => 'groups#edit', as: :edit_group
  resources :group_options
  resources :activities

  # 控制台
  get 'dashboard' => 'dashboard#index', as: :dashboard
  DashboardController::AdminModels.each do |category|
    get "dashboard/admin/#{category}" => "dashboard#admin_#{category}", as: "admin_#{category}"
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end
end

app/views/resources/_block_list.html.erb
<div class='row'>
  <% resources.each do |resource| %>
    <% next if not resource.image? %>
    <div class='col-md-4 col-sm-6 col-xs-12'>
      <a href='<%= url_for [ resource.resourceable, resource ] %>' class='thumbnail'>
        <%= image_tag resource.file.url, class: 'img-responsive center-block' %>
      </a>
    </div>
  <% end %>
</div>

app/views/resources/_profile_left.html.erb
<ul class='vertical-clean-list'>
  <li>
    <%= t('activerecord.attributes.resource.user') %>:
    <%= link_to @resource.user.name, @resource.user %>
  </li>
  <li>
    <%= number_to_human_size @resource.file.file.size %>
  </li>
  <li>
    <%=
      link_to fa_icon('download', text: t('action.download')),
      @resource.file.url
    %>
    <% if policy(@resource).update? %>
      <%= link_to fa_icon('edit', text: t('action.edit')), [ :edit, @resource ] %>
    <% end %>
    <% if policy(@resource).destroy? %>
      <%=
        link_to fa_icon('trash', text: t('action.delete')), @resource, method: :delete,
        data: { confirm: t('message.are_you_sure_to_delete?', thing: t('activerecord.models.resource')) }
      %>
    <% end %>
  </li>
  <li>
    <%= render 'collections/collect_button', collectable: @resource %>
  </li>
</ul>

app/views/resources/_rename.html.erb
<%= simple_form_for resource, html: { class: 'form-inline', style: 'display: inline;' }, remote: true do |f| %>
  <%= f.input_field :name, label: false %>
<% end %>

<script type='text/javascript'>
  // 当用户点击其它地方时，退出修改。
  $('body').on('click', function() {
    $('form#edit_resource_<%= resource.id %>').remove();
    $('a[href="/resources/<%= resource.id %>"]').show();
  });
</script>

app/views/resources/_table_list.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th width="100"><%= t('activerecord.attributes.resource.name') %></th>
      <th width="100"><%= t('activerecord.attributes.resource.user') %></th>
      <th width="200"><%= t('activerecord.attributes.resource.created_at') %></th>
    </tr>
  </thead>
  <tbody>
    <% resources.each do |resource| %>
      <tr class='clickable-row' data-href='<%= url_for [ resource.resourceable, resource ] %>'>
        <td><%= resource.name %></td>
        <td><%= resource.user.name %></td>
        <td><%= resource.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resources/create.js.erb
<% if @resource.errors.empty? %>
  var resourceNames = [];
  var resourceIDs = []
  $('#resource-board-table td span').each(function() {
    resourceNames.push($(this).text());
    resourceIDs.push($(this).parent().parent().attr('id'));
  })
  // 关闭modal。
  $('#add-resource').modal('hide');
  // 按序搜索将新创建的文件夹插入到当前列表的哪一行后面。
  var inserted = false;
  for (i = 0; i < resourceNames.length; i++) {
    if (resourceNames[i] > '<%= @resource.name %>') {
      $('#' + resourceIDs[i]).before("<%=
        j render 'resource_board/resource_table_row', resource: @resource
      %>");
      inserted = true;
      break;
    }
  }
  if (!inserted) {
    if (resourceIDs.length == 0) {
      $('#resource-board-table').append("<%=
        j render 'resource_board/resource_table_row', resource: @resource
      %>")
    } else {
      $('#' + resourceIDs[resourceIDs.length-1]).after("<%=
        j render 'resource_board/resource_table_row', resource: @resource
      %>");
    }
  }
<% else %>
  // 处理错误。
  <% if @resource.errors.include? :file %>
    showValidationError('fileinput', '<%= @resource.errors.messages[:file].first %>');
  <% elsif @resource.errors.include? :name %>
    showValidationError('fileinput', '<%= @resource.errors.messages[:name].first %>');
  <% end %>
<% end %>

app/views/resources/destroy.js.erb
$('#resource-<%= @resource.id %>').hide();

app/views/resources/edit.html.erb
<% content_for :title, t('action.edit')+t('activerecord.models.resource') %>

<% content_for :center_column do %>
  <%= render 'form' %>
<% end %>

app/views/resources/new.js.erb
// 清空表单。
$('input#resource_folder_id').attr('value', '<%= @resource.folder_id %>');
$('input#resource_resourceable_type').attr('value', '<%= @resource.resourceable_type %>');
$('input#resource_resourceable_id').attr('value', '<%= @resource.resourceable_id %>');
// 弹出一个modal。
$('div#add-resource').modal();

app/views/resources/show.html.erb
<% content_for :title, @resource.name %>
<% add_breadcrumb @resource.name, resource_path(@resource) %>

<% content_for :left_column do %>
  <%= render 'profile_left' %>
<% end %>

<% content_for :center_column do %>
  <dl class='resource-show'>
    <dt><%= @resource.name %></dt>
    <dd>
      <div class='center'>
        <%= fa_icon 'spinner spin', style: 'font-size: 100px;', id: 'spinner' %>
        <%= preview @resource %>
      </div>
      <div class='description' style='margin-top: 1em;'>
        <%= @resource.description %>
      </div>
    </dd>
  </dl>
  <dl>
    <dt></dt>
    <dd><%= render 'comments/list', commentable: @resource %></dd>
  </dl>
<% end %>

app/views/resources/update.js.erb
<% case @update_action %>
<% when :move %>
  $('#resource-<%= @resource.id %>').remove();
<% when :rename %>
  $('a[href="/resources/<%= @resource.id %>"]').text('<%= @resource.name %>').show();
  $('form#edit_resource_<%= @resource.id %>').remove();
<% end %>